### ISSUE TITLE
预览图 in readme.md?

### ISSUE THREAD

**Issue by PYUDNG** [Clearpole/VideoYouX#33]
如题。
预览图可以帮助新来者快速直观地了解这个项目，并且更容易吸引star。
我现在甚至都不知道是否要star一个。

**Comment by misaka-13766** [comment]
@PYUDNG 软件设计以及其他功能等目前还在草创阶段，待设计定型了会把设计图上传的，可以先下载CI版本体验下，谢谢理解与支持～

**Comment by PYUDNG** [comment]
@misaka-13766 刚刚下载CI版本（[CI #208](https://github.com/Clearpole/VideoYouX/actions/runs/5542047081)）试了试，第一次打开时第一个界面上右下角的“现在开始”按钮点击就无反应。我到系统设置里直接给予存储权限后重新打开应用，点“现在开始”还是没反应。是我下载的CI版本不对吗？

附加信息
系统：华为鸿蒙2.0.0.168
没反应 是指点击后没有实际效果，按钮点击特效还是有的，背景动画也在持续播放，整个应用并没有卡死

**Comment by misaka-13766** [comment]
@PYUDNG 最新CI版本仅供测试新版引导页用，竖屏播放功能在7月8日及之前的构建版本中
